on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: show versions
      run: |
        python --version
        clang-format --version
    - name: run test
      run: |
        ./build.sh
        git diff --exit-code

  run-example:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: run example
      run: |
        pip install -e .
        pushd example
        ./tutorial.sh
        popd

  validaton:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            compile: g++ -std=gnu++2a -O2 -Wall -Wextra -Wno-unused-result -Werror
            stack-limit: 1048576
          - os: ubuntu-latest
            compile: g++ -std=gnu++14 -O2 -Wall -Wextra -Wno-unused-result -Werror
            stack-limit: 1048576
          - os: macos-11.0
            compile: g++ -std=c++17 -O2 -Wall -Wextra -Wno-unused-result -Werror
            stack-limit: 65532

    needs: [check-format, run-example]
    runs-on: ${{ matrix.os }}
    env:
      COMPILE: ${{ matrix.compile }}

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      id: cache-workspace
      with:
        path: ~/.workspace
        key: ${{ runner.os }}-workspace

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: install dependencies
      run: |
        pip install -U pip
        pip install -U online-judge-tools

    - name: show versions
      run: |
        g++ --version
        python --version

    - name: run test
      run: |
        ulimit -s ${{ matrix.stack-limit }}
        ./scripts/test.sh cpp
